version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password